import type { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function MetaTags({ ...props }: Metadata) {
  return (
    <>
      {/* <meta name="description" content={metadata.description} /> */}
    </>
  );
}
